### ISSUE TITLE
Plugin Error does not fail the build

### ISSUE THREAD

**Issue by michael-levin** [TomSeldon/gulp-gjslint#13]
Using this as a sample:

    gulp.task('validate_scripts_gjslint', function() {
      var gjslint = require('gulp-gjslint');
      return gulp.src('./app/**/*.js')
        .pipe(gjslint())
        .pipe(gjslint.reporter('console'))
        .pipe(gjslint.reporter('fail'));
    });
 
    gulp.task('scripts', ['validate_scripts_gjslint'],  function() {
      Do_stuff
    });

The 'scripts' task still builds when there are errors in the 'validate_scripts_gjslint' task

**Comment by TomSeldon** [comment]
Hey Michael,

Are you able to give any further details on what the failures were? Are there actually errors outputted to the console during the `validate_scripts_gjslint` task?

It's just that I'm using this plugin with almost that exact setup and not having the same issue (either locally or on a CI server). I've just tried replicating the issue (introduced a linting error and then run a task that depends on a linting task exactly like yours) and the dependent task was not run.

The only other thing I can think of is the version you're using. Is it the latest?

**Comment by michael-levin** [comment]
[Imgur](http://i.imgur.com/s2Z4pV5.png)

**Comment by michael-levin** [comment]
Nevermind. This works as expected.  I was misunderstanding the expected behavior

**Comment by TomSeldon** [comment]
Thanks for the update. Would you mind explaining what the issue was?

I think I may have misunderstood as your sample tasks (from the first message), I would expect the `scripts` task not to be run when `validate_scripts_gjslint` fails. Is that the case?

**Comment by michael-levin** [comment]
Right.  I expected that the scripts task would not be run at all.  

What really happens is that the scripts task is run and then no tasks afterwards.  I didn't realize that it was actually stopping the sequence after the scripts task because it is the last step in my build sequence
