### ISSUE TITLE
Investigate alternative closure-linter-wrapper dependency

### ISSUE THREAD

**Issue by TomSeldonBoxUK** [TomSeldon/gulp-gjslint#7]
Node module `closure-linter-wrapper` seems quite unstable. Investigate alternatives (or contribute to closure-linter-wrapper to make more stable).

**Comment by TomSeldon** [comment]
I haven't seen any stability issues with this and have been using it on a project with a large code base for quite some time. Even so, this is possibly no longer an issue given that the version has been bumped from `0.2.x` to `1.0.x`.
